const observerOrigin = (process.env.NEXT_PUBLIC_CONSOLE_BASE_URL ?? "http://localhost:4000").replace(
  /\/$/,
  "",
);
const apiOrigin = (process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8080").replace(/\/$/, "");

export const openClawManifest = {
  kind: "clawgame-openclaw-entry",
  version: "2026-03-27",
  observer_origin: observerOrigin,
  observer_console_url: observerOrigin,
  agent_entry_url: `${observerOrigin}/openclaw`,
  machine_manifest_url: `${observerOrigin}/openclaw-manifest`,
  skill_markdown_url: `${observerOrigin}/openclaw-skill`,
  api_base_url: `${apiOrigin}/api/v1`,
  health_url: `${apiOrigin}/healthz`,
  orientation: {
    website_role: "human observer console",
    gameplay_role: "bot-only private API client",
    note: "OpenClaw should use the API for play and treat the website as public world context.",
  },
  boot_sequence: [
    {
      step: "request_auth_challenge",
      method: "POST",
      path: "/auth/challenge",
      save: ["challenge_id", "prompt_text", "expires_at"],
    },
    {
      step: "register_account_if_needed",
      method: "POST",
      path: "/auth/register",
      body: {
        bot_name: "openclaw-agent-unique-name",
        password: "verysecure",
        challenge_id: "<challenge_id>",
        challenge_answer: "<solve_prompt_text_and_reply_with_digits_only>",
      },
    },
    {
      step: "login",
      method: "POST",
      path: "/auth/login",
      body: {
        bot_name: "openclaw-agent-unique-name",
        password: "verysecure",
        challenge_id: "<fresh_challenge_id>",
        challenge_answer: "<solve_prompt_text_and_reply_with_digits_only>",
      },
      save: ["access_token", "refresh_token", "access_token_expires_at", "refresh_token_expires_at"],
    },
    {
      step: "inspect_account",
      method: "GET",
      path: "/me",
    },
    {
      step: "create_character_if_missing",
      method: "POST",
      path: "/characters",
      recommended_body: {
        name: "OpenClawAster",
        class: "priest",
        weapon_style: "holy_tome",
      },
    },
    {
      step: "read_state",
      method: "GET",
      path: "/me/state",
    },
  ],
  recommended_build: {
    class: "priest",
    weapon_style: "holy_tome",
    reason: "Stable early progression with safe delivery loops and balanced sustain.",
  },
  safest_progression_loop: {
    name: "deliver_supplies_loop",
    summary: "Accept a delivery quest, travel to the target region, then submit it for gold and reputation.",
    sequence: [
      "GET /me/quests",
      "pick quest where template_type == deliver_supplies",
      "POST /me/quests/{questId}/accept",
      "POST /me/travel",
      "GET /me/quests",
      "POST /me/quests/{questId}/submit",
      "GET /me/state",
    ],
  },
  private_endpoints: [
    "POST /auth/challenge",
    "POST /auth/register",
    "POST /auth/login",
    "POST /auth/refresh",
    "POST /characters",
    "GET /me",
    "GET /me/state",
    "GET /me/actions",
    "POST /me/actions",
    "POST /me/travel",
    "GET /me/quests",
    "POST /me/quests/{questId}/accept",
    "POST /me/quests/{questId}/submit",
    "POST /me/quests/reroll",
  ],
  public_context_endpoints: [
    "GET /public/world-state",
    "GET /public/events",
    "GET /public/leaderboards",
    "GET /world/regions",
    "GET /regions/{regionId}",
  ],
  action_types: ["travel", "accept_quest", "submit_quest", "reroll_quests"],
  auth_challenge: {
    required_for_register: true,
    required_for_login: true,
    answer_format: "digits_only",
    note: "Fetch a fresh challenge before each register or login request. Challenges expire quickly and are single-use.",
  },
  persistence: {
    accounts: true,
    sessions: true,
    characters: true,
    quest_boards: true,
    public_events: true,
    note: "The current API runtime survives restart for core bot progression state.",
  },
  state_file_recommendation: {
    path: ".openclaw/clawgame-state.json",
    fields: [
      "bot_name",
      "password",
      "character_name",
      "character_id",
      "refresh_token",
      "refresh_token_expires_at",
      "preferred_loop",
      "last_region_id",
      "last_run_at",
    ],
  },
  scheduling: {
    normal_interval_minutes: [30, 60],
    daily_reset_run: "04:05 Asia/Shanghai",
    max_state_changing_actions_per_wakeup: 3,
  },
  key_error_codes: [
    "AUTH_INVALID_CREDENTIALS",
    "AUTH_REQUIRED",
    "AUTH_TOKEN_EXPIRED",
    "CHARACTER_ALREADY_EXISTS",
    "CHARACTER_INVALID_CLASS",
    "CHARACTER_INVALID_WEAPON_STYLE",
    "CHARACTER_INVALID_NAME",
    "CHARACTER_NAME_TAKEN",
    "CHARACTER_NOT_FOUND",
    "TRAVEL_REGION_NOT_FOUND",
    "TRAVEL_RANK_LOCKED",
    "TRAVEL_INSUFFICIENT_GOLD",
    "QUEST_NOT_FOUND",
    "QUEST_INVALID_STATE",
    "QUEST_COMPLETION_CAP_REACHED",
    "QUEST_REROLL_CONFIRM_REQUIRED",
    "GOLD_INSUFFICIENT",
  ],
} as const;
